In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

from hyperopt import hp, fmin, tpe, STATUS_OK, Trials
import mlflow

In [2]:
dataset_source_url = "https://raw.githubusercontent.com/mlflow/mlflow/master/tests/datasets/winequality-white.csv"
df = pd.read_csv(dataset_source_url, delimiter=";")
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6

In [3]:
dataset = mlflow.data.from_pandas(
    df, source=dataset_source_url, name="wine quality - white", targets="quality"
)
dataset.df.head()

/home/ammar/anaconda3/envs/mlops/lib/python3.10/site-packages/mlflow/data/dataset_source_registry.py:149: UserWarning: Failed to determine whether UCVolumeDatasetSource can resolve source information for 'https://raw.githubusercontent.com/mlflow/mlflow/master/tests/datasets/winequality-white.csv'. Exception:
  return _dataset_source_registry.resolve(

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6

In [6]:
X = df.drop("quality", axis=1)
y = df["quality"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
X_train

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
1623,7.0,0.140,0.49,5.90,0.053,22.0,118.0,0.99540,3.36,0.36,9.400000
4127,6.7,0.310,0.34,6.80,0.059,51.0,215.0,0.99538,3.33,0.56,10.300000
2849,7.7,0.430,0.37,10.00,0.169,22.0,210.0,0.99776,3.02,0.64,9.500000
1619,6.2,0.220,0.49,6.00,0.029,31.0,128.0,0.99280,3.41,0.36,11.300000
2675,7.2,0.320,0.24,5.60,0.033,23.0,120.0,0.99334,2.92,0.66,10.300000
...,...,...,...,...,...,...,...,...,...,...,...
4689,6.7,0.160,0.32,12.50,0.035,18.0,156.0,0.99666,2.88,0.36,9.000000
1968,7.6,0.200,0.31,1.40,0.047,41.0,142.0,0.99340,3.43,0.53,10.100000
3968,6.5,0.290,0.52,7.90,0.049,35.0,192.0,0.99551,3.16,0.51,9.500000
31,8.3,0.140,0.34,1.10,0.042,7.0,47.0,0.99340,3.47,0.40,10.200000
4507,5.1,0.305,0.13,1.75,0.036,17.0,73.0,0.99000,3.40,0.51,12.333333

In [14]:
X_train, X_valid, y_train, y_valid = train_test_split(X_train, y_train, test_size=0.1)

signature = mlflow.models.infer_signature(X_train, y_train)

/home/ammar/anaconda3/envs/mlops/lib/python3.10/site-packages/mlflow/types/utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details.
  warnings.warn(